version: '3'

services: 

  server:
    build: 
      context: server
    container_name: schedule-creator-server
    working_dir: /app
    networks: 
      - schedule-creator-app
    volumes: 
      - ./server:/app
    tty: true
    ports: 
      - "3000:3000"
    command: npm run start

  client:
    build: 
      context: client
    container_name: schedule-creator-client
    working_dir: /app
    networks: 
      - schedule-creator-app
    volumes: 
      - ./client:/app
    tty: true
    ports: 
      - "5173:5173"
    command: npm run start

  nginx:
    build: 
      context: nginx
    container_name: schedule-creator
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - schedule-creator-app
    depends_on:
       - server
       - client
  
networks: 
  schedule-creator-app:
    driver: bridge