version: '3'

services: 

  backend:
    build: 
      context: server
    container_name: schedule-creator-server
    working_dir: /app
    networks: 
      - schedule-creator-app
    tty: true
    ports: 
      - "3000:3000"
    command: npm run start

  frontend:
    build: 
      context: client
    container_name: schedule-creator-client
    working_dir: /app
    networks: 
      - schedule-creator-app
    tty: true
    ports: 
      - "5173:5173"
    command: npm run serve

  nginx:
    build: 
      context: nginx
    container_name: schedule-creator-nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - schedule-creator-app
    depends_on:
       - backend
       - frontend
  
networks: 
  schedule-creator-app:
    driver: bridge