enum AcademicPeriodEnum {
  NONE = "NONE",
  FIRST_SEMESTER = "FIRST_SEMESTER",
  SECOND_SEMESTER = "SECOND_SEMESTER",
  SUMMER = "SUMMER",
  FIRST_TRIMESTER = "FIRST_TRIMESTER",
  SECOND_TRIMESTER = "SECOND_TRIMESTER",
  THIRD_TRIMESTER = "THIRD_TRIMESTER",
  TRANSITION_SEMESTER = "TRANSITION_SEMESTER",
  SENIORHIGH_TRANSITION_SEMESTER_1 = "SENIORHIGH_TRANSITION_SEMESTER_1",
  SENIORHIGH_TRANSITION_SEMESTER_2 = "SENIORHIGH_TRANSITION_SEMESTER_2",
}

export default AcademicPeriodEnum;
