name: Deploy to EC2
on:
    push: 
        branches: 
            - main
            - bs--workflow-refactor
    workflow_dispatch: 
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: NodeJS setup
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
            
            - name: SSH into EC2 instance for deployment
              uses: appleboy/ssh-action@master
              with:
                host: "${{ secrets.EC2_HOST }}"
                username: "${{ secrets.EC2_USERNAME }}"
                key: "${{ secrets.EC2_SSH_KEY }}"
                script: |
                  rm -rf schedule-creator
                  git clone https://github.com/0-BSCode/schedule-creator.git
                  cd schedule-creator
                  npm run prod